language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    # - "3.9"
install:
  - sudo apt update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  # - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip setuptools numpy scipy matplotlib pandas nose coverage xlsxwriter h5py coveralls
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip setuptools numpy scipy matplotlib pandas coverage xlsxwriter h5py coveralls
  - pip install nose
  - conda activate test-environment
  - python setup.py install
script:
    - python setup.py nosetests
after_success:
    - coveralls
