language: python
python:
    - "3.10"
    - "3.11"
install:
  - sudo apt update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip setuptools numpy scipy matplotlib pandas coverage xlsxwriter h5py coveralls
  - conda activate test-environment
  - python -m pip install test_requirements.txt
  - python -m build -n
  - python -m pip install -e .
script:
  - /bin/sh run_tests.sh
after_success:
    - coveralls
