name: pyyeti
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy>=1.10
  - scipy>=0.17
  - matplotlib>=1.5
  - pandas>=0.17
  - sphinx>=4.0
  - ipython>=4
  - notebook>=4
  - numba
  - sphinx-copybutton
  - sphinx-toggleprompt
  - pygments
  - openpyxl
